"""Structured Agent output schemas."""

from quantagent.agents.schemas.views import (
    AllocationStance,
    ArgumentPoint,
    Catalyst,
    DimensionView,
    DimScore,
    Disagreement,
    FinancialHealth,
    InputsSummary,
    MacroView,
    MarketBrief,
    RankedSector,
    RankedStock,
    RedFlag,
    RiskNote,
    SectorDimensions,
    SectorImpact,
    SectorView,
    StockCandidate,
    StockDimensions,
    StockView,
    ThemeLifecycle,
    UpcomingEvent,
    WatchItem,
)

__all__ = [
    "AllocationStance",
    "ArgumentPoint",
    "Catalyst",
    "DimensionView",
    "DimScore",
    "Disagreement",
    "FinancialHealth",
    "InputsSummary",
    "MacroView",
    "MarketBrief",
    "RankedSector",
    "RankedStock",
    "RedFlag",
    "RiskNote",
    "SectorDimensions",
    "SectorImpact",
    "SectorView",
    "StockCandidate",
    "StockDimensions",
    "StockView",
    "ThemeLifecycle",
    "UpcomingEvent",
    "WatchItem",
]
